"""buat tabel

Revision ID: 4c1ff8c63e51
Revises: 
Create Date: 2024-04-12 17:08:03.315159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1ff8c63e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('satuan', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_table('officer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('no_identitas', sa.String(length=25), nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pekerjaan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('komitmen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('jumlah_barang', sa.Integer(), nullable=False),
    sa.Column('satuan', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum(), nullable=False),
    sa.Column('tanggal_pengembalian', sa.DateTime(), nullable=False),
    sa.Column('id_material', sa.BigInteger(), nullable=True),
    sa.Column('id_pekerjaan', sa.BigInteger(), nullable=True),
    sa.Column('id_officer', sa.BigInteger(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['id_officer'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['id_pekerjaan'], ['pekerjaan.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('no_identitas', sa.String(length=25), nullable=False),
    sa.Column('no_hp', sa.String(length=20), nullable=False),
    sa.Column('id_unit', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_unit'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_hp')
    )
    op.create_table('picking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('no_reservasi', sa.String(length=10), nullable=False),
    sa.Column('jumlah_barang', sa.Integer(), nullable=False),
    sa.Column('satuan', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum(), nullable=False),
    sa.Column('id_material', sa.BigInteger(), nullable=True),
    sa.Column('id_pekerjaan', sa.BigInteger(), nullable=True),
    sa.Column('id_officer', sa.BigInteger(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['id_officer'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['id_pekerjaan'], ['pekerjaan.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_reservasi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picking')
    op.drop_table('pengguna')
    op.drop_table('komitmen')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('unit')
    op.drop_table('pekerjaan')
    op.drop_table('officer')
    op.drop_table('material')
    # ### end Alembic commands ###
