"""buat tabel

Revision ID: e18d33d31106
Revises: bae9b6284ab6
Create Date: 2024-04-12 17:37:15.214469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18d33d31106'
down_revision = 'bae9b6284ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('komitmen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('jumlah_barang', sa.Integer(), nullable=False),
    sa.Column('satuan', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PROSES', 'COMPLETE', 'FAILED', name='status'), nullable=False),
    sa.Column('tanggal_pengembalian', sa.DateTime(), nullable=False),
    sa.Column('id_material', sa.BigInteger(), nullable=True),
    sa.Column('id_pekerjaan', sa.BigInteger(), nullable=True),
    sa.Column('id_officer', sa.BigInteger(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['id_officer'], ['officer.id'], ),
    sa.ForeignKeyConstraint(['id_pekerjaan'], ['pekerjaan.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('komitmen')
    # ### end Alembic commands ###
